export const FETCH_STOCKS = 'FETCH_STOCKS';
export const FETCH_STOCKS_SUCCESS = 'FETCH_STOCKS_SUCCESS';
export const FETCH_STOCKS_FAILURE = 'FETCH_STOCKS_FAILURE';

export const UPDATE_SELECTED_STOCKS = 'UPDATE_SELECTED_STOCKS';

export const ADD_SELECTED_STOCK_DATE = 'ADD_SELECTED_STOCK_DATE';